name: Deploy Angular App to EC2

on:
  push:
    branches: [main]  # Trigger on push to the main branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_TYPESCRIPT_ES: false  # Disable TypeScript (ESLint) validation
          VALIDATE_TYPESCRIPT_STANDARD: false  # Disable TypeScript (Standard) validation
          VALIDATE_YAML: false  # Disable YAML validation
          DISABLE_GITHUB_ACTIONS: true

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  # Use Node.js 18.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Angular app
      - name: Build Angular app
        run: npm run build -- --configuration=production

      # Step 5: Deploy to EC2 using SCP
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}          # EC2 public IP
          username: ${{ secrets.EC2_USERNAME }}  # EC2 username (e.g., ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}        # Private SSH key
          source: "dist/pipeline/*"             # Source files (built Angular app)
          target: "/var/www/html/angular-app"   # Target directory on EC2

      # Step 6: Restart Nginx on EC2
      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}          # EC2 public IP
          username: ${{ secrets.EC2_USERNAME }}  # EC2 username (e.g., ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}        # Private SSH key
          script: |
            sudo systemctl restart nginx         # Restart Nginx to serve the new app
